### ISSUE TITLE
license (bump for issue 9)

### ISSUE THREAD

**Issue by feliscatusmeows** [0x3C50/Coffee#10]
Issue 9 was closed, but we still do not have permission to run or download coffee client legally. Please fix this https://choosealicense.com/no-permission/#:~:text=no%20permission%20from%20the%20creators%20of%20the%20software%20to%20use%2C%20modify%2C%20or%20share%20the%20software

**Comment by 0x3C50** [comment]
i fucking put the license ages ago wdym, which license should i put now

**Comment by feliscatusmeows** [comment]
idk, mabye a source-avilable license such as https://github.com/pmachapman/unrar/blob/master/license.txt but modified for this project
