### ISSUE TITLE
License????????????????????????????????????

### ISSUE THREAD

**Issue by feliscatusmeows** [0x3C50/Coffee#9]
The license says "all rights reserved" which supposedly means that keeping copies of the code or running coffee client is illegal? Also if this still has code from the old atomic client or cornos which I think were gpl then I do not know if it is legal to change the license to all rights reserved. I think you might want to review this license thingy because it confuses me. 

https://choosealicense.com/no-permission/#:~:text=no%20permission%20from%20the%20creators%20of%20the%20software%20to%20use%2C%20modify%2C%20or%20share%20the%20software

**Comment by master7720** [comment]
License's do nothing

**Comment by 0x3C50** [comment]
no permission license is good

**Comment by feliscatusmeows** [comment]
I do not think you read my issue, my issue is that your license does not give permission to download or run coffee and uses code from atomic and cornos which were gpl.

**Comment by feliscatusmeows** [comment]
bump
